### ISSUE TITLE
Question:  Getting Container Statistics

### ISSUE THREAD

**Issue by rwmajor2** [dmandalidis/docker-client#113]
Hi @dmandalidis.  Quick question as you are now my expert on this client SDK.  :)

When I call docker.stats(containerId), it returns to me statistics and there is always about a 1-2 second wait time.  This is equivalent to what you experience with the Docker CLI.  However, with the Docker CLI, I am say `docker stats` (meaning show stats for all containers) and this experiences the same 1-2 second wait time and then displays all containers and resource consumption.

With this SDK, only `stats(containerId)` exists.  The only way I know how to do this is loop over all the containers I have running and call it on each container.  However, in this scenario, I experience the same 1-2 second delay but on each time it gets called.  For a Docker environment running many containers (e.g. 50), this takes an excruciatingly long time.

Do you have any suggestions on how to improve this so that it behaves similar to the Docker CLI?

Below is my java code.
```java
 public JSONArray getAllContainerStatsLocal() throws AdminException {

    DockerClient docker;
    try {
      docker = DefaultDockerClient.fromEnv().build();
    } catch (DockerCertificateException e) {
      logger.debug(e.getLocalizedMessage());
      throw new AdminException(TuringAdminLogCode.FAILED_TO_ESTABLISH_DOCKER_ENVIRONMENT.message(), e);
    }

    try {
      JSONArray array = new JSONArray();
      ContainerStats stats = null;
      Container[] cns = getAllContainersLocal(ServerIPUtil.getFQLocalHost());
      for (int i = 0; i < cns.length; i++) {
        stats = docker.stats(cns[i].getContainerId());   //   <--  Slow line
        ContainerStatistics cs = null;
        if (stats != null) {
          cs = createContainerStatisticsObject(stats, cns[i].getId(), cns[i].getContainerId());
          array.put(cs.toJSON());
        }
      }
      return array;
    } catch (Exception e) {
      logger.debug(e);
      throw new AdminException(e);
    } finally {
      if (null != docker) {
        docker.close();
      }
    }
  }
```

**Comment by dmandalidis** [comment]
Hi @rwmajor2 ,

Unfortunately the plain `docker stats` (without a container) is a docker cli enhancement. This project acts as a Java binding over the REST API instead which doesn't have such an endpoint. Adding such features from other REST implementations will probably lead to confusion and maintenance chaos. Sorry :)

**Comment by rwmajor2** [comment]
@dmandalidis Thanks for the feedback.
