### ISSUE TITLE
Support for specifying SWARM Generic Resources

### ISSUE THREAD

**Issue by kelseym** [dmandalidis/docker-client#155]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

## Description

Docker SWARM nodes can advertise availability of generic resources, which can be requested by and used to constrain services.  Support for specifying generic resources on Swarm service requests could support [allocating GPU resources.](https://medium.com/@kyeongwook.ma/deploy-nvidia-docker-to-docker-swarm-service-in-10-mins-4ba603048e85)  This could be implemented by extending the ResourceRequirements type to include key-value pairs.

## Software:

- `docker version`: Docker version 19.03.6
- Spotify's docker-client version: 3.2.0

**Comment by dmandalidis** [comment]
Hey @kelseym,

Could you please give it a try? Note that since `Resources` was shared between limits and reservations, merging this will trigger a major version update and thus an API break

**Comment by kelseym** [comment]
This works great. Thanks for your effort!
