### ISSUE TITLE
Make it possible or default to or default to restricting containers from acquiring additional privileges

### ISSUE THREAD

**Issue by tony--** [dmandalidis/docker-client#203]
FEATURE REQUEST

## Description
**Problem**

Without setting no_new_priv bit in kernel, a process can gain additional privileges for example via suid or sgid bits. This way a lot of operations can become dangerous because of the possibility to subvert unprivileged binaries.
Common Weakness Enumeration

**Solution**

Restrict the container from acquiring additional privileges via suid or sgid bits.no_new_priv prevents LSMs like SELinux from transitioning to process labels that have access not allowed to the current process.

e.g.,
`docker run --rm -it --security-opt=no-new-privileges ubuntu bash`

## How to reproduce

N/A

## What do you expect

Add the capability as a parameter or default to this behavior.
Thanks!

**Comment by dmandalidis** [comment]
Hi @tony--,

It's already supported through `ContainerConfig#hostConfig#SecurityOpt` (add `no-new-privilileges`). We would rather not enforce such defaults (even if reasonable) I believe, because users would always need to do something extra to revert them.

_edit_: syntax
