### ISSUE TITLE
RHEL8 and podman support

### ISSUE THREAD

**Issue by rwmajor2** [dmandalidis/docker-client#230]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature Request

## Description

We are trying to use your SDK for running Tomcat application on RHEL 8.  Unfortunately, RedHat 8.x doesn't support traditional Docker (thus docker daemon) running; it uses something called podman instead.  Any thoughts on if this Java SDK can be used in this scenario??

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by dmandalidis** [comment]
Hi @rwmajor2,

Sorry but we are not going to support podman or anything else than Docker.
