### ISSUE TITLE
Add HostConfig.Init support when creating a container

### ISSUE THREAD

**Issue by arminbalalaie** [dmandalidis/docker-client#36]
Based on the docker API changelog, from version 1.25, Docker added HostConfig.Init field to POST /containers/create to run an init inside the container that forwards signals and reaps processes. Right now, it is not possible to configure this field through the HostConfig.Builder class. It'd be great to add support for this.

**Comment by dmandalidis** [comment]
Hi @arminbalalaie 

Thanks. Unfortunately you 're blocked by https://github.com/dmandalidis/docker-client/pull/43 for the moment, once I merged it I 'll review your changes.
