### ISSUE TITLE
conflicting jaxrs/jersey versions in 5.x

### ISSUE THREAD

**Issue by mattnelson** [dmandalidis/docker-client#391]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug

## Description

After `5.0.0`[^1] the versions of jaxrs/jersey defined in the POM are not compatible with each other. jaxrs was upgraded to `3.0.0` which includes the package rename[^2] from `javax.*` to `jakarta.*`
[^1]: https://github.com/dmandalidis/docker-client/blob/master/CHANGELOG.md#500
[^2]: https://github.com/eclipse-ee4j/jaxrs-api/releases

## How to reproduce

Use dependency management for `jakarta.ws.rs:jakarta.ws.rs-api:2.1.6` with the enforcer upper bounds rule[^3]
[^3]: https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html

```
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for jakarta.ws.rs:jakarta.ws.rs-api:2.1.6 paths to dependency are:
+-myproject
  +-org.glassfish.jersey.media:jersey-media-json-jackson:2.35
    +-org.glassfish.jersey.ext:jersey-entity-filtering:2.35
      +-jakarta.ws.rs:jakarta.ws.rs-api:2.1.6 (managed) <-- jakarta.ws.rs:jakarta.ws.rs-api:3.0.0
```

## What do you expect

Apply one of these changes, but not both:

* Downgrade `version.jaxrs` to `2.1.6`, the last release of `jakarta.ws.rs-api` which uses the `javax` package.
* Upgrade `version.jersey` to 3.0.0+

## Workaround

Revert back to docker-client `4.x`

**Comment by dmandalidis** [comment]
Hi @mattnelson 

You are right. I had in mind to avoid updating Jersey to 3+ until RESTeasy releases their JAXRS package-rename release, but I missed this.
