### ISSUE TITLE
Update jersey to > 2.28

### ISSUE THREAD

**Issue by dmandalidis** [dmandalidis/docker-client#45]
It seems there is an issue to jersey versions > 2.28. We have a test at `DefaultDockerClientTest#testBuildInterruption` which constantly fails with jersey > 2.28 for no obvious (to me reason). I 've placed several log stmts to see what happens and it seems that somehow there's a huge delay between shutting down the executor and have the callable throw an `InterruptedException` (more than 40-50s). I think it's something which broke in Jersey `AsyncInvoker` but I cannot be sure since I 've never used Jersey before and requires much more time to investigate.

Removing the test is considered since there's no guarantee that an executor's tasks are cancelled (cancelled on a best-effort basis), but I 'd like to give it a try.

**Comment by rwmajor2** [comment]
@dmandalidis Does this have to do with trying to use the docker-client in multiple threads?  From our testing, it doesn't seem it is thread safe and we are constantly having to create instances all over the place to try and work around.

**Comment by dmandalidis** [comment]
Hi @rwmajor2, it could be but I didn't put significant effort in it. Seems to be thread-related but I plan to dig further into it next week since the behavior of a single test was very weird. Will take a look also into the thead-safety matter you mentioned through this
