### ISSUE TITLE
Commons base 64 import without dependency (assumes it comes with jersey)?

### ISSUE THREAD

**Issue by d2a-raudenaerde** [dmandalidis/docker-client#493]
** BUG REPORT**:

## Description

There is a apache-commons Base64 import form the apache commons, which causes a  `java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64` when switching from Jersey 3.0.5 to Jersey 3.0.6
![image](https://user-images.githubusercontent.com/5213150/187151546-2ae31f04-b136-4867-8166-ad8382c3a7eb.png)

Is is still in 3.0.5, via de apache-connector
 org.glassfish.jersey.connectors:jersey-apache-connector:jar:3.0.5:compile

**Comment by dmandalidis** [comment]
Hi @d2a-raudenaerde,

You are right, docker-client should explicitly pull commons-codec dependency instead. Please expect a patch release very soon.

**Comment by d2a-raudenaerde** [comment]
You could also just use the Base64 from java.util?

**Comment by dmandalidis** [comment]
Yes, requires some minor extra work though so I skipped this on purpose to revisit it in the near future (feel free to open a PR)
