### ISSUE TITLE
Capabilities should be a list of lists of strings

### ISSUE THREAD

**Issue by luksow** [dmandalidis/docker-client#531]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

## Description

Capabilities in DeviceRequests should be `List[List[String]]` instead of `List[String]` according to the docs: https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate. Setting any capabilities now results in parsing error.

## How to reproduce

```scala
    val docker = new JerseyDockerClientBuilder()
    .uri(new URI("unix:///var/run/docker.sock"))
    .build

    val hostConfig = HostConfig
    .builder()
    .deviceRequests(List(DeviceRequest.builder().driver("nvidia").count(-1).capabilities(List("gpu").asJava).build).asJava)
    .build

    val containerConfig = ContainerConfig
      .builder()
      .hostConfig(hostConfig)
      .image("test")
      .build

    val creation = docker.createContainer(containerConfig)
    docker.startContainer(creation.id)
```

**Comment by dmandalidis** [comment]
hi @luksow,

Yeap, you 're right. Thanks for this
