### ISSUE TITLE
Can't connect via unix socket when Java http proxy is set

### ISSUE THREAD

**Issue by andrewbrock-sahmri** [dmandalidis/docker-client#601]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

## Description

Connection to docker host uses HTTP proxy settings even if connecting via a unix socket. In the Spotify version of this library this bug was tracked in https://github.com/spotify/docker-client/issues/982 but I don't think it was every resolved

## How to reproduce

Set the http.proxyHost, http.proxyPort, https.proxyHost, https.proxyPort variables. Configure the docker-client library to connect via unix:///var/run/docker.sock

## What do you expect

Connection to occur

## What happened instead

Request gets pushed to the HTTP proxy, which errors as the protocol is incorrect

## Software:

- `docker version`:     5:23.0.6-1 (server)
- Spotify's docker-client version: 6.0.4 (client) (am using it via the XNAT Container Service https://bitbucket.org/xnatdev/container-service/src/master/)

## Full backtrace

None.

**Comment by dmandalidis** [comment]
Hey, thanks for reporting this. I have a couple of questions:

* can you post a code snippet showing how the Docker client is built in your case? (couldn't find any reference to that in the xnatdev repo you linked)
* are you using the Jersey or the RESTeasy flavour?

thanks

**Comment by andrewbrock-sahmri** [comment]
Hi,

You can see its creation here:
https://bitbucket.org/xnatdev/container-service/src/75d61531cd0d916c6060c3df7dcdc684523abbf8/src/main/java/org/nrg/containers/api/DockerControlApi.java#lines-1326

(seems to be using Jersey)
I've let the XNAT devs know about this issue also.

**Comment by dmandalidis** [comment]
Hi again @andrewbrock-sahmri ,

I think I got it. Quick workaround is to use `.useProxy(false)` in that builder code snippet, even though I agree proxy usage doesn't make sense for non-http URIs (I will work on that and come back to you)

**Comment by dmandalidis** [comment]
v7.0.3 containing the fix is on its way

**Comment by andrewbrock-sahmri** [comment]
@dmandalidis fantastic, thanks!
