### ISSUE TITLE
Add support for --gpus new in Docker 19.0.3

### ISSUE THREAD

**Issue by rwmajor2** [dmandalidis/docker-client#75]
**Is this a BUG REPORT or FEATURE REQUEST?**:  FEATURE REQUEST

## Description

As of Docker 19.0.3, there is a new option to specify GPU capabilities during `docker run`.  It would be nice to include that here.
https://docs.docker.com/config/containers/resource_constraints/

## Software:
```
      --gpus gpu-request               GPU devices to add to the
                                       container ('all' to pass all GPUs)
```

**Comment by dmandalidis** [comment]
Hi @rwmajor2 , can you test the branch containing the feature?

I found some useful info at https://github.com/NVIDIA/nvidia-docker/issues/1035

**Comment by rawlsstew** [comment]
Thank you for your work on this.  
I am interested in starting GPU aware containers in a SWARM configuration. Can these Device Requests be used to make certain GPU resources available to containers running on SWARM nodes?
