### ISSUE TITLE
Question:  Connection reset by peer errors

### ISSUE THREAD

**Issue by rwmajor2** [dmandalidis/docker-client#76]
Hi @dmandalidis, when using the Docker-client, I see this a lot.  Do you know if your PR https://github.com/dmandalidis/docker-client/pull/69 would help address these stack traces?  It seems trying to read Docker logs has been problematic for quite some time.

`
java.lang.RuntimeException: java.io.IOException: Connection reset by peer at com.spotify.docker.client.shaded.com.google.common.base.Throwables.propagate(Throwables.java:240) at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58) at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35) at com.spotify.docker.client.shaded.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) at com.spotify.docker.client.shaded.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) at com.spotify.docker.client.DefaultLogStream.readFully(DefaultLogStream.java:77) at com.esri.arcgis.turing.admin.system.ContainersManager.launchContainer(ContainersManager.java:248) at 
....
`

**Comment by dmandalidis** [comment]
Hi @rwmajor2,

No it won't solve such errors as it simply replaces autovalue with immutables not Guava entirely. However, this seems like a bug to me, does it happen consistently?

**Comment by rwmajor2** [comment]
@dmandalidis One more random question; sorry this is not on topic of this issue.  Should I always be diligent to docker.close() any docker connections I create?  Seems like I have a memory leak in my application but I noticed I don't .close() any of my connections that I create.

**Comment by dmandalidis** [comment]
@rwmajor2 as a general rule of thumb you should always close the connections you open and if you don't, you have the ideal memory leak candidate :) However, constructing a new `DockerClient` each time is very expensive since two `javax.ws.rs.client.Client` are created along. The Jersey implementation guarantees thread safety but I will need to check if the `DefaultDockerClient` has the same guarantees which is actual the answer to your comment in #45.

**Comment by rwmajor2** [comment]
@dmandalidis Ok, thanks.  I had tried to reuse a DockerClient instance for each thread but kept running into problems reusing it.  But, perhaps I didn't know what I was doing exactly.

**Comment by dmandalidis** [comment]
Hi @rwmajor2 

Spent some time investigating the thread safety issues you mentioned here and in #45. To my understanding, the `DefaultDockerClient` is thread-safe. I 'm closing this issue, and if I 'm wrong, please open a bug with a code-block reproducing the problem.
