### ISSUE TITLE
Conflict due to org.glassfish.jersey.connectors.jersey-apache-connector 3.1.8 and jakarta.ws.rs-api 4.0.0

### ISSUE THREAD

**Issue by jjohnstn** [dmandalidis/docker-client#773]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

## Description

After trying to move to docker-client 8.0.1 we have a conflict caused by the move to jakarta.ws.rs-api 4.0.0

No resolution report for the bundle. Bundle was not resolved because of a uses constraint violation.
org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.linuxtools.docker.core [osgi.identity; type="osgi.bundle"; version:Version="5.16.0.202408061822"; osgi.identity="org.eclipse.linuxtools.docker.core"; singleton:="true"] because it is exposed to package 'jakarta.ws.rs' from resources jakarta.ws.rs-api [osgi.identity; type="osgi.bundle"; version:Version="4.0.0"; osgi.identity="jakarta.ws.rs-api"] and jakarta.ws.rs-api [osgi.identity; type="osgi.bundle"; version:Version="3.1.0"; osgi.identity="jakarta.ws.rs-api"] via two dependency chains.

Chain 1:
org.eclipse.linuxtools.docker.core [osgi.identity; type="osgi.bundle"; version:Version="5.16.0.202408061822"; osgi.identity="org.eclipse.linuxtools.docker.core"; singleton:="true"]
import: (&(osgi.wiring.package=jakarta.ws.rs)(version>=2.0.1))
|
export: osgi.wiring.package: jakarta.ws.rs
jakarta.ws.rs-api [osgi.identity; type="osgi.bundle"; version:Version="4.0.0"; osgi.identity="jakarta.ws.rs-api"]

Chain 2:
org.eclipse.linuxtools.docker.core [osgi.identity; type="osgi.bundle"; version:Version="5.16.0.202408061822"; osgi.identity="org.eclipse.linuxtools.docker.core"; singleton:="true"]
import: (osgi.wiring.package=org.glassfish.jersey.apache.connector)
|
export: osgi.wiring.package=org.glassfish.jersey.apache.connector; uses:=jakarta.ws.rs.client
org.glassfish.jersey.connectors.jersey-apache-connector [osgi.identity; type="osgi.bundle"; version:Version="3.1.8"; osgi.identity="org.glassfish.jersey.connectors.jersey-apache-connector"]
import: (&(osgi.wiring.package=jakarta.ws.rs.client)(&(version>=3.1.0)(!(version>=4.0.0))))
|
export: osgi.wiring.package: jakarta.ws.rs.client; uses:=jakarta.ws.rs
export: osgi.wiring.package=jakarta.ws.rs
jakarta.ws.rs-api [osgi.identity; type="osgi.bundle"; version:Version="3.1.0"; osgi.identity="jakarta.ws.rs-api"]

@dmandalidis Were you able to get around this problem?

## How to reproduce

This is found when we try and aggregate the Eclipse simrel.

## What do you expect

No conflicts.

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server] N/A
- Spotify's docker-client version: [Add docker-client version here] 8.0.1

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by dmandalidis** [comment]
Hi @jjohnstn,

I think docker-client needs to downgrade given that Jersey client is not yet compatible with Jakarta 4.x (or work around it through an osgi.properties). I will fix it as soon as possible.
