### ISSUE TITLE
Deprecations from v1.46 not correct?

### ISSUE THREAD

**Issue by sauliusvl** [dmandalidis/docker-client#791]
[This commit](https://github.com/dmandalidis/docker-client/commit/4b39c4f358ec19327fc224931acdde38c708cd94) marked fields such as `hostname` and `image` on `ContainerConfig` deprecated. However, reading the docker API docs [regarding the deprecation](https://docs.docker.com/reference/api/engine/version-history/#deprecated-config-fields-in-get-imagesnamejson-response) I interpreted it differently: these fields will be deprecated from the `/images/{name}/json` response (which are there due to technical docker implementation details), but they will remain in the container description output, which is what this class is now used for, so I _think_ it gives a false positive.

**Comment by dmandalidis** [comment]
Hi @sauliusvl ,

Thanks for this. You are right, the problem is that we are reusing `ContainerConfig` both in the container info endpoints and the image info endpoint (which is not correct). I will look into it soon.

Thanks again
